### ISSUE TITLE
Can this be used with JDK 1.8 or above?

### ISSUE THREAD

**Issue by yuhang-lin** [kidoz/jiprof#2]
I was able to compile it but it failed to execute with JDK 1.8.

**Comment by yuhang-lin** [comment]
Below is the error message:
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.VerifyError: Expecting a stackmap frame at branch target 41
Exception Details:
  Location:
    example/TraceExample.exceptionMethod()Ljava/lang/String; @7: invokestatic
  Reason:
    Expected stackmap frame at this location.
  Bytecode:
    0x0000000: 120f 1294 b800 16b8 0062 3f1e 1400 8271
    0x0000010: 0994 9a00 14bb 003b 5912 96b7 0098 120f
    0x0000020: 1294 b800 1bbf a700 1712 0f12 9412 99b8
    0x0000030: 0036 4b12 9b12 0f12 94b8 001b b012 9d12
    0x0000040: 0f12 94b8 001b b0                      
  Exception Handler Table:
    bci [7, 38] => handler: 41
  Stackmap Table:
    same_frame(@38)
    same_locals_1_stack_item_frame(@50,Object[#59])
    same_frame(@61)

	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
	at java.lang.Class.privateGetMethodRecursive(Class.java:3048)
	at java.lang.Class.getMethod0(Class.java:3018)
	at java.lang.Class.getMethod(Class.java:1784)
	at sun.launcher.LauncherHelper.validateMainClass(LauncherHelper.java:650)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:632)
Controller -- shuttingdown

**Comment by kidoz** [comment]
I updated gradle version and tested with JDK 1.8. Build work with some warnings. All change in master branch.

**Comment by yuhang-lin** [comment]
Thanks for the update! I was able to compile the project with JDK 1.8. I am wondering if it is possible to record the entry and exist time of methods?
